version: '3.8'

services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.13.4  # Atualizar para 8.x
    networks:
      - internal_network
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic                  # Usuário configurado no ES
      - ELASTICSEARCH_PASSWORD=admin123                  # Senha configurada no ES
    restart: always

networks:
  internal_network:
    external: true
