version: '3.8'

services:
  kibana:
    container_name: kibana_1
    image: "docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}"  # Mesma vers칚o do ES
    networks:
      - internal_network
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}  # Usu치rio via vari치vel
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}  # Senha via vari치vel
    restart: always

networks:
  internal_network:
    external: true  # 游깷 Rede j치 criada externamente
