version: '3.8'

services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.0
    networks:
      - internal_network
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    restart: always

networks:
  internal_network:
    external: true
